routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/






Auth::routes();

Route::get('/', 'PageController@home');
Route::get('/project', 'PageController@project');
Route::get('/agent', 'PageController@agent');
Route::get('/expo', 'PageController@expo');
Route::get('/contact', 'PageController@contact');
Route::get('/brochure', 'PageController@brochure');
Route::get('post', 'PostController@index');
Route::get('post/{slug}', 'PostController@show')->name('post.show');
Route::get('program-info', 'PageController@programInfo');

Route::get('admin/home', 'HomeController@index');
Route::group(['middleware'=>'auth','namespace'=>'Admin','prefix' => 'admin','as' => 'admin.'],function (){
    Route::resource('post', 'PostController');
    Route::resource('agent', 'AgentController');    
    Route::resource('location', 'AgentLocationController');
    Route::resource('brochure', 'BrochureController');
    Route::resource('contact', 'ContactController');
    Route::resource('expo', 'ExpoController');    
    Route::resource('project', 'ProjectController');
    Route::resource('user', 'UserController');    
    Route::resource('about', 'AboutController');
    Route::resource('logo', 'LogoController');
    Route::resource('gift', 'GiftController');
    Route::resource('block', 'BlockController');
    Route::get('program-info','PageController@programInfo');
});

resources/views/admin/location/create.blade.php
@extends('adminlte::page')

@section('css')
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css">
@stop

@section('title', 'Agent Location - Tambah')

@section('content_header')
    <h1>Add Agent Location</h1>
@stop

@section('content')
    <div class="row">
        {!! Form::open(['route'=>'admin.location.store']) !!}

        <div class="col-lg-8">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Tambah Agent Location</h3>
                </div>
                <div class="box-body">
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> Ada inputan yang salah.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    
                    <div class="form-group">
                        <label for="">Name</label>
                        {!! Form::text('name',null, ['class'=>'form-control']) !!}
                    </div>                                  

                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a href="{{ URL::previous() }}" class="btn btn-warning" style="padding: 6px 20px;">Back</a>

                </div>
            </div>
        </div>
        {!! Form::close() !!}

    </div>


@stop

@section('js')

@stop

resources/views/admin/location/edit.blade.php
@extends('adminlte::page')

@section('css')
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/css/bootstrap-datepicker.css">
@stop

@section('title', 'Agent Location - Edit')

@section('content_header')
    <h1>Edit Agent Location</h1>
@stop

@section('content')
    <div class="row">
        {!! Form::model($location,['route'=>['admin.location.update',$location->id],'method'=>'PATCH']) !!}

        <div class="col-lg-8">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Edit Agent Location</h3>
                </div>
                <div class="box-body">
                    @if (count($errors) > 0)
                        <div class="alert alert-danger">
                            <strong>Whoops!</strong> Ada inputan yang salah.<br><br>
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    
                    <div class="form-group">
                        <label for="">Name</label>
                        {!! Form::text('name',null, ['class'=>'form-control']) !!}
                    </div>         

                    <button type="submit" class="btn btn-primary">Update</button>
                    <a href="{{ URL::previous() }}" class="btn btn-warning" style="padding: 6px 20px;">Back</a>

                </div>
            </div>
        </div>

        {!! Form::close() !!}

    </div>


@stop

@section('js')
@stop

resources/views/admin/location/index.blade.php
@extends('adminlte::page')

@section('title', 'Agent Location - All')

@section('css')
    <meta name="csrf-token" content="{{ csrf_token() }}">
@stop

@section('content_header')
    <h1>Data Agent Location</h1>
@stop

@section('content')
    <div class="row">
        <div class="col-lg-6 ">
            <div class="row">
                <div class="col-lg-9 ">
                    <form role="search">
                        <div class="input-group">
                            <input type="text" value="" name="q" class="form-control">
                            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">Cari Data</button>
              </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>


        <br>
        <br>
        <br>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Data Agent Location</h3>
                </div>
                <table class="table table-bordered">
                    <tr>
                        <th>Agent Location</th>                        
                        <th style="width:200px;">Action</th>
                    </tr>
                    @foreach ($locations as $location)
                        <tr>
                            <td>{{$location->name}}</td>
                            <td>
                                <a href="{!! route('admin.location.edit',$location->id)!!}"><button class="btn btn-primary"><i class="fa fa fa-edit"></i></button></a>
                                <a onclick="checkDelete({{$location->id}})"  class="btn btn-danger" >Delete
                                </a>
                            </td>
                        </tr>
                    @endforeach
                </table>
                <div class="box-footer clearfix">
                    {!! $paginate !!}
                </div>
            </div>



        </div>
    </div>
@stop

@section('js')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/7.0.7/sweetalert2.all.min.js"></script>
    <script>
        function checkDelete(id) {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            swal({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.value) {
                $.ajax({
                    url:" {{ url('admin/location/')}}/"+id,
                    type: 'DELETE',
                })
                .done(function(res) {
                    swal(
                        'Deleted!',
                        'Your file has been deleted.',
                        'success'
                    )
                    location.reload();
                })
            }
        })
        }
    </script>
@stop